In [ ]:
import pandas as pd
import numpy as np

Importing required libraries for data cleaning and analysis

In [ ]:
df = pd.read_csv("zomato.csv")

Loading the Zomato restaurant dataset

> Add blockquote

In [ ]:
df.head()
# Displaying first 5 records to understand dataset structure

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [ ]:
df.info()
df.shape
# Checking number of rows, columns and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   object
 3   restaurant type        7105 non-null   object
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   object
 8   table booking          7105 non-null   object
 9   cuisines type          7105 non-null   object
 10  area                   7105 non-null   object
 11  local address          7105 non-null   object
dtypes: float64(2), int64(3), object(7)
memory usage: 666.2+ KB

(7105, 12)

In [ ]:
df.isnull().sum()
# Checking missing values in each column

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

rate (out of 5) → missing values
avg cost (two people) → missing values

In [ ]:
df.rename(columns={
    'restaurant name':'restaurant_name',
    'restaurant type':'restaurant_type',
    'rate (out of 5)':'rating',
    'num of ratings':'num_ratings',
    'avg cost (two people)':'cost_for_two',
    'cuisines type':'cuisine_type',
    'local address':'local_address'
}, inplace=True)
# Renaming columns for consistency and easier coding

In [ ]:
df.drop(
    columns=['Unnamed: 0.1','Unnamed: 0'],
    inplace=True
)
# Removing unwanted index columns created during dataset export

In [ ]:
# Filling missing values in rating column with median
# Median is used because it is less affected by extreme values

df['rating'] = df['rating'].fillna(
    df['rating'].median()
)

# Filling missing values in cost_for_two column with median
# This preserves all restaurant records for analysis

df['cost_for_two'] = df['cost_for_two'].fillna(
    df['cost_for_two'].median()
)
df[['rating', 'cost_for_two']].isnull().sum()

rating          0
cost_for_two    0
dtype: int64

 Missing values were replaced using median values.
 Median is preferred over mean because it is less sensitive to outliers.
 This allows us to keep all restaurant records instead of deleting rows.

In [ ]:
df.drop_duplicates(inplace=True)
# Removing duplicate restaurant records

In [ ]:
text_columns = [
    'restaurant_name',
    'restaurant_type',
    'cuisine_type',
    'area',
    'local_address'
]

for col in text_columns:
    df[col] = df[col].str.strip().str.title()
    # Cleaning text fields by removing extra spaces
# and standardizing capitalization

In [ ]:
df.dtypes
df['rating'] = pd.to_numeric(
    df['rating'],
    errors='coerce'
)

df['num_ratings'] = pd.to_numeric(
    df['num_ratings'],
    errors='coerce'
)

df['cost_for_two'] = pd.to_numeric(
    df['cost_for_two'],
    errors='coerce'
)
# Ensuring numerical columns have correct data types

In [ ]:
df['cost_per_person'] = (
    df['cost_for_two'] / 2
)
# Calculating approximate cost per person

In [ ]:
df['rating_category'] = pd.cut(
    df['rating'],
    bins=[0,3,4,5],
    labels=['Low','Average','Excellent']
)
# Categorizing restaurants based on ratings

In [ ]:
df.head()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_name  7105 non-null   object
 1   restaurant_type  7105 non-null   object
 2   rating           7105 non-null   float64
 3   num_ratings      7105 non-null   int64
 4   cost_for_two     7105 non-null   float64
 5   online_order     7105 non-null   object
 6   table booking    7105 non-null   object
 7   cuisine_type     7105 non-null   object
 8   area             7105 non-null   object
 9   local_address    7105 non-null   object
 10  cost_per_person  7105 non-null   float64
 11  rating_category  7105 non-null   category
dtypes: category(1), float64(3), int64(1), object(7)
memory usage: 617.8+ KB

restaurant_name    0
restaurant_type    0
rating             0
num_ratings        0
cost_for_two       0
online_order       0
table booking      0
cuisine_type       0
area               0
local_address      0
cost_per_person    0
rating_category    0
dtype: int64

In [ ]:
df.to_csv(
    'cleaned_dataset.csv',
    index=False
)
# Exporting cleaned dataset for SQL and Power BI